name = "tick-take-client"
type = "webpack"
account_id = "74a16798d58c8dadab19ffcf255a0f25"
workers_dev = true

[site]
bucket = "./dist/tick-take-app"
entry-point = "workers-site"

[env.stage]
workers_dev = false
# The ID of your domain you're deploying to
zone_id = "be05a106f4f6ef00bcbcfdc33ddb78da"
# The route pattern your Workers application will be served at
route = "tick-take.fictionaldev.com/*"
