name: Deploy

on:
  push:
    branches:
      - master
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache ~/.npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: npm install
        run: npm i --no-audit
      - name: npm build
        run: npm run build
      - name: Upload build artefact
        uses: actions/upload-artifact@v1
        with:
          name: angular-app
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download build artefact
        uses: actions/download-artifact@v1
        with:
          name: angular-app
          path: dist
      - uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "stage"
